using .env and playwright-testing.env files

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -5,7 +5,7 @@ on:
   pull_request:
     branches: [ main, master ]
 jobs:
-  test:
+  WalletGenerationTests:
     timeout-minutes: 60
     runs-on: ubuntu-latest
     steps:
@@ -13,15 +13,6 @@ jobs:
       uses: actions/checkout@v2
     - name: Set up Docker
       uses: docker/setup-buildx-action@v2
-    - name: Modify and Show Docker Compose File
-      run: |
-        mkdir -p ./docker/doichain/db
-        chmod 777 ./docker/doichain/db
-        # Remove the specific volume line and save changes in place
-        sed -i '/- \.\/\.doichain\/:\/home\/doichain\/\.doichain\//d' ./docker/doichain/docker-compose-regtest.yml
-        # Display the modified file contents
-        echo "📄 Displaying modified docker-compose-regtest.yml contents..."
-        cat ./docker/doichain/docker-compose-regtest.yml
     - name: Set up Docker
       uses: hoverkraft-tech/compose-action@v2.0.2
       with:
@@ -30,15 +21,18 @@ jobs:
       run: |
         echo "🔍 Checking Docker Containers..."
         docker compose -f "docker/doichain/docker-compose-regtest.yml" ps
+    - name: Run Playwright tests
+      run: |
+        docker compose -f docker/doichain/docker-compose-regtest.yml --env-file ./docker/doichain/playwright-testing.env up -d
     - name: Modify Run Command and Run Playwright tests
       run: |
-        sed -i.bak \
-          -e 's/^    # command: \["npx", "playwright", "test"\]/    command: \["npx", "playwright", "test"\]/' \
-          -e 's/^    command: \["echo", "finished building"\]/     # command: \["echo", "finished building"\]/' \
-          ./docker/doichain/docker-compose-regtest.yml
-        sed -i.bak \
-          -e '/build:/,+2d' \
-          ./docker/doichain/docker-compose-regtest.yml
-        cat ./docker/doichain/docker-compose-regtest.yml
-        set -e  # Exit immediately if a command exits with a non-zero status
-        docker compose -f "docker/doichain/docker-compose-regtest.yml" up playwright
+        # sed -i.bak \
+        #   -e 's/^    # command: \["npx", "playwright", "test"\]/    command: \["npx", "playwright", "test"\]/' \
+        #   -e 's/^    command: \["echo", "finished building"\]/     # command: \["echo", "finished building"\]/' \
+        #   ./docker/doichain/docker-compose-regtest.yml
+        # sed -i.bak \
+        #   -e '/build:/,+2d' \
+        #   ./docker/doichain/docker-compose-regtest.yml
+        # cat ./docker/doichain/docker-compose-regtest.yml
+        # set -e  # Exit immediately if a command exits with a non-zero status
+        # docker compose -f "docker/doichain/docker-compose-regtest.yml" up playwright
